name: Heroku pack
author_name: Masahiro Iuchi
author_link: https://github.com/masiuchi
version: 0.01

applications:
  upgrade:
    type: 0

  cms:
    callbacks:
      init_app: $Heroku::Heroku::BackupStaticFiles::restore

tasks:
  BackupStaticFiles:
    label: Back up static files
    frequency: 300
    code: $Heroku::Heroku::BackupStaticFiles::backup
