requires 'DBI';
requires 'DBD::Pg';
requires 'Imager';

requires 'Plack';
requires 'CGI::PSGI';
requires 'CGI::Emulate::PSGI';
requires 'CGI::Compile';
requires 'XMLRPC::Transport::HTTP::Plack';

# Heroku.pack
requires 'IO::All';
requires 'Plack::Middleware::ReverseProxy';
